apiVersion: v2
name: django-polls
description: helm chart for deploying django polls application
maintainers:
  - name: dahl
    email: 8tima18@gmail.com

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: 18.1.3
    repository: oci://registry-1.docker.io/bitnamicharts
    alias: postgresdb
    condition: postgresdb.enabled
