# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- if .Values.database.usePostgres }}
  DB_USERNAME: {{ .Values.database.postgresSettings.username | quote }}
  DB_PASSWORD: {{ .Values.database.postgresSettings.password | quote }}
  {{- end }}
