apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-sqlite-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/k8s/{{ .Release.Name }}-sqlite-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-sqlite-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
